<?php
/**
 * ContactsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientHub\Test\Api;

use \ClientHub\Configuration;
use \ClientHub\ApiException;
use \ClientHub\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for contactSummaryEndpointApiV1ContactsUuidSummaryGet
     *
     * Contact Summary Endpoint.
     *
     */
    public function testContactSummaryEndpointApiV1ContactsUuidSummaryGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for convertContactEndpointApiV1ContactsUuidConvertPost
     *
     * Convert Contact Endpoint.
     *
     */
    public function testConvertContactEndpointApiV1ContactsUuidConvertPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createContactEndpointApiV1ContactsPost
     *
     * Create Contact Endpoint.
     *
     */
    public function testCreateContactEndpointApiV1ContactsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteContactEndpointApiV1ContactsUuidDelete
     *
     * Delete Contact Endpoint.
     *
     */
    public function testDeleteContactEndpointApiV1ContactsUuidDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePreferenceApiV1ContactsUuidPreferencesKeyDelete
     *
     * Delete Preference.
     *
     */
    public function testDeletePreferenceApiV1ContactsUuidPreferencesKeyDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getContactEndpointApiV1ContactsUuidGet
     *
     * Get Contact Endpoint.
     *
     */
    public function testGetContactEndpointApiV1ContactsUuidGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMarketingOptoutsApiV1ContactsUuidMarketingGet
     *
     * Get Marketing Optouts.
     *
     */
    public function testGetMarketingOptoutsApiV1ContactsUuidMarketingGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listContactsEndpointApiV1ContactsGet
     *
     * List Contacts Endpoint.
     *
     */
    public function testListContactsEndpointApiV1ContactsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPreferencesApiV1ContactsUuidPreferencesGet
     *
     * List Preferences.
     *
     */
    public function testListPreferencesApiV1ContactsUuidPreferencesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setPreferenceApiV1ContactsUuidPreferencesKeyPut
     *
     * Set Preference.
     *
     */
    public function testSetPreferenceApiV1ContactsUuidPreferencesKeyPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateContactEndpointApiV1ContactsUuidPut
     *
     * Update Contact Endpoint.
     *
     */
    public function testUpdateContactEndpointApiV1ContactsUuidPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateMarketingOptoutsApiV1ContactsUuidMarketingPut
     *
     * Update Marketing Optouts.
     *
     */
    public function testUpdateMarketingOptoutsApiV1ContactsUuidMarketingPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
