<?php
/**
 * LookupApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientHub\Test\Api;

use \ClientHub\Configuration;
use \ClientHub\ApiException;
use \ClientHub\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LookupApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LookupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for lookupEmailApiV1LookupEmailEmailGet
     *
     * Lookup Email.
     *
     */
    public function testLookupEmailApiV1LookupEmailEmailGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for lookupPhoneApiV1LookupPhoneNumberGet
     *
     * Lookup Phone.
     *
     */
    public function testLookupPhoneApiV1LookupPhoneNumberGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
