<?php
/**
 * OrdersApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientHub\Test\Api;

use \ClientHub\Configuration;
use \ClientHub\ApiException;
use \ClientHub\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrdersApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrdersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for changeOrderStatusApiV1OrdersUuidStatusPost
     *
     * Change Order Status.
     *
     */
    public function testChangeOrderStatusApiV1OrdersUuidStatusPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrderApiV1OrdersPost
     *
     * Create Order.
     *
     */
    public function testCreateOrderApiV1OrdersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrderApiV1OrdersUuidDelete
     *
     * Delete Order.
     *
     */
    public function testDeleteOrderApiV1OrdersUuidDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrderApiV1OrdersUuidGet
     *
     * Get Order.
     *
     */
    public function testGetOrderApiV1OrdersUuidGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrdersApiV1OrdersGet
     *
     * List Orders.
     *
     */
    public function testListOrdersApiV1OrdersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
