<?php
/**
 * OrganizationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientHub\Test\Api;

use \ClientHub\Configuration;
use \ClientHub\ApiException;
use \ClientHub\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createOrganizationApiV1OrganizationsPost
     *
     * Create Organization.
     *
     */
    public function testCreateOrganizationApiV1OrganizationsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationApiV1OrganizationsUuidDelete
     *
     * Delete Organization.
     *
     */
    public function testDeleteOrganizationApiV1OrganizationsUuidDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationApiV1OrganizationsUuidGet
     *
     * Get Organization.
     *
     */
    public function testGetOrganizationApiV1OrganizationsUuidGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrganizationsApiV1OrganizationsGet
     *
     * List Organizations.
     *
     */
    public function testListOrganizationsApiV1OrganizationsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganizationApiV1OrganizationsUuidPut
     *
     * Update Organization.
     *
     */
    public function testUpdateOrganizationApiV1OrganizationsUuidPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
