<?php
/**
 * SettingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClientHub\Test\Api;

use \ClientHub\Configuration;
use \ClientHub\ApiException;
use \ClientHub\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SettingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SettingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getSettingsApiV1SettingsGet
     *
     * Get Settings.
     *
     */
    public function testGetSettingsApiV1SettingsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateSettingsApiV1SettingsPut
     *
     * Update Settings.
     *
     */
    public function testUpdateSettingsApiV1SettingsPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
