<?php
/**
 * InlineAffiliationCreateTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ClientHub\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * InlineAffiliationCreateTest Class Doc Comment
 *
 * @category    Class
 * @description Embedded in ContactCreate for one-shot contact + affiliation.
 * @package     ClientHub
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineAffiliationCreateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineAffiliationCreate"
     */
    public function testInlineAffiliationCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "organization_uuid"
     */
    public function testPropertyOrganizationUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "role_title"
     */
    public function testPropertyRoleTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "seniority"
     */
    public function testPropertySeniority()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_decision_maker"
     */
    public function testPropertyIsDecisionMaker()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_primary"
     */
    public function testPropertyIsPrimary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
