<?php
/**
 * LookupMatchChannelPrefTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.6
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ClientHub\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LookupMatchChannelPrefTest Class Doc Comment
 *
 * @category    Class
 * @description LookupMatchChannelPref
 * @package     ClientHub
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LookupMatchChannelPrefTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LookupMatchChannelPref"
     */
    public function testLookupMatchChannelPref()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preferred"
     */
    public function testPropertyPreferred()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "opt_in"
     */
    public function testPropertyOptIn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
