# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CommCreate(BaseModel):
    """
    CommCreate
    """ # noqa: E501
    contact_uuid: StrictStr
    channel: StrictStr
    direction: StrictStr
    occurred_at: StrictStr
    subject: Optional[StrictStr] = None
    body: Optional[StrictStr] = None
    order_uuid: Optional[StrictStr] = None
    external_message_id: Optional[StrictStr] = None
    created_by: Optional[StrictStr] = None
    external_refs_json: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["contact_uuid", "channel", "direction", "occurred_at", "subject", "body", "order_uuid", "external_message_id", "created_by", "external_refs_json"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if subject (nullable) is None
        # and model_fields_set contains the field
        if self.subject is None and "subject" in self.model_fields_set:
            _dict['subject'] = None

        # set to None if body (nullable) is None
        # and model_fields_set contains the field
        if self.body is None and "body" in self.model_fields_set:
            _dict['body'] = None

        # set to None if order_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.order_uuid is None and "order_uuid" in self.model_fields_set:
            _dict['order_uuid'] = None

        # set to None if external_message_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_message_id is None and "external_message_id" in self.model_fields_set:
            _dict['external_message_id'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['created_by'] = None

        # set to None if external_refs_json (nullable) is None
        # and model_fields_set contains the field
        if self.external_refs_json is None and "external_refs_json" in self.model_fields_set:
            _dict['external_refs_json'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contact_uuid": obj.get("contact_uuid"),
            "channel": obj.get("channel"),
            "direction": obj.get("direction"),
            "occurred_at": obj.get("occurred_at"),
            "subject": obj.get("subject"),
            "body": obj.get("body"),
            "order_uuid": obj.get("order_uuid"),
            "external_message_id": obj.get("external_message_id"),
            "created_by": obj.get("created_by"),
            "external_refs_json": obj.get("external_refs_json")
        })
        return _obj


