# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clienthub.models.contact_create_email import ContactCreateEmail
from clienthub.models.contact_create_phone import ContactCreatePhone
from typing import Optional, Set
from typing_extensions import Self

class ContactCreate(BaseModel):
    """
    ContactCreate
    """ # noqa: E501
    first_name: StrictStr
    last_name: StrictStr
    contact_type: Optional[StrictStr] = 'prospect'
    organization_uuid: Optional[StrictStr] = None
    display_name: Optional[StrictStr] = None
    phones: Optional[List[ContactCreatePhone]] = None
    emails: Optional[List[ContactCreateEmail]] = None
    marketing_sources: Optional[List[StrictStr]] = None
    data_source: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["first_name", "last_name", "contact_type", "organization_uuid", "display_name", "phones", "emails", "marketing_sources", "data_source"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContactCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in phones (list)
        _items = []
        if self.phones:
            for _item_phones in self.phones:
                if _item_phones:
                    _items.append(_item_phones.to_dict())
            _dict['phones'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in emails (list)
        _items = []
        if self.emails:
            for _item_emails in self.emails:
                if _item_emails:
                    _items.append(_item_emails.to_dict())
            _dict['emails'] = _items
        # set to None if organization_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.organization_uuid is None and "organization_uuid" in self.model_fields_set:
            _dict['organization_uuid'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if data_source (nullable) is None
        # and model_fields_set contains the field
        if self.data_source is None and "data_source" in self.model_fields_set:
            _dict['data_source'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContactCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "contact_type": obj.get("contact_type") if obj.get("contact_type") is not None else 'prospect',
            "organization_uuid": obj.get("organization_uuid"),
            "display_name": obj.get("display_name"),
            "phones": [ContactCreatePhone.from_dict(_item) for _item in obj["phones"]] if obj.get("phones") is not None else None,
            "emails": [ContactCreateEmail.from_dict(_item) for _item in obj["emails"]] if obj.get("emails") is not None else None,
            "marketing_sources": obj.get("marketing_sources"),
            "data_source": obj.get("data_source")
        })
        return _obj


