# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.settings_update import SettingsUpdate

class TestSettingsUpdate(unittest.TestCase):
    """SettingsUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettingsUpdate:
        """Test SettingsUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettingsUpdate`
        """
        model = SettingsUpdate()
        if include_optional:
            return SettingsUpdate(
                business_name = '',
                business_type = '',
                timezone = '',
                currency = '',
                tax_rate = 1.337,
                phone = '',
                email = '',
                website = ''
            )
        else:
            return SettingsUpdate(
        )
        """

    def testSettingsUpdate(self):
        """Test SettingsUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
