# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.api_key_create import ApiKeyCreate

class TestApiKeyCreate(unittest.TestCase):
    """ApiKeyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiKeyCreate:
        """Test ApiKeyCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiKeyCreate`
        """
        model = ApiKeyCreate()
        if include_optional:
            return ApiKeyCreate(
                name = 'Default key'
            )
        else:
            return ApiKeyCreate(
        )
        """

    def testApiKeyCreate(self):
        """Test ApiKeyCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
