# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.comm_create import CommCreate

class TestCommCreate(unittest.TestCase):
    """CommCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommCreate:
        """Test CommCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommCreate`
        """
        model = CommCreate()
        if include_optional:
            return CommCreate(
                contact_uuid = '',
                channel = '',
                direction = '',
                occurred_at = '',
                subject = '',
                body = '',
                order_uuid = '',
                external_message_id = '',
                created_by = '',
                external_refs_json = {
                    'key' : null
                    }
            )
        else:
            return CommCreate(
                contact_uuid = '',
                channel = '',
                direction = '',
                occurred_at = '',
        )
        """

    def testCommCreate(self):
        """Test CommCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
