# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization_api_v1_organizations_post(self) -> None:
        """Test case for create_organization_api_v1_organizations_post

        Create Organization
        """
        pass

    def test_delete_organization_api_v1_organizations_uuid_delete(self) -> None:
        """Test case for delete_organization_api_v1_organizations_uuid_delete

        Delete Organization
        """
        pass

    def test_get_organization_api_v1_organizations_uuid_get(self) -> None:
        """Test case for get_organization_api_v1_organizations_uuid_get

        Get Organization
        """
        pass

    def test_list_organizations_api_v1_organizations_get(self) -> None:
        """Test case for list_organizations_api_v1_organizations_get

        List Organizations
        """
        pass

    def test_update_organization_api_v1_organizations_uuid_put(self) -> None:
        """Test case for update_organization_api_v1_organizations_uuid_put

        Update Organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
