# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.status_change import StatusChange

class TestStatusChange(unittest.TestCase):
    """StatusChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusChange:
        """Test StatusChange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusChange`
        """
        model = StatusChange()
        if include_optional:
            return StatusChange(
                status = '',
                changed_by = '',
                notes = ''
            )
        else:
            return StatusChange(
                status = '',
        )
        """

    def testStatusChange(self):
        """Test StatusChange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
