# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.source_update import SourceUpdate

class TestSourceUpdate(unittest.TestCase):
    """SourceUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SourceUpdate:
        """Test SourceUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SourceUpdate`
        """
        model = SourceUpdate()
        if include_optional:
            return SourceUpdate(
                name = '',
                source_type = '',
                domain = '',
                description = ''
            )
        else:
            return SourceUpdate(
        )
        """

    def testSourceUpdate(self):
        """Test SourceUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
