# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.api.invoices_api import InvoicesApi


class TestInvoicesApi(unittest.TestCase):
    """InvoicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoicesApi()

    def tearDown(self) -> None:
        pass

    def test_create_invoice_api_v1_invoices_post(self) -> None:
        """Test case for create_invoice_api_v1_invoices_post

        Create Invoice
        """
        pass

    def test_get_invoice_api_v1_invoices_uuid_get(self) -> None:
        """Test case for get_invoice_api_v1_invoices_uuid_get

        Get Invoice
        """
        pass

    def test_list_invoices_api_v1_invoices_get(self) -> None:
        """Test case for list_invoices_api_v1_invoices_get

        List Invoices
        """
        pass

    def test_record_payment_api_v1_invoices_uuid_payments_post(self) -> None:
        """Test case for record_payment_api_v1_invoices_uuid_payments_post

        Record Payment
        """
        pass


if __name__ == '__main__':
    unittest.main()
