# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.api.marketing_sources_api import MarketingSourcesApi


class TestMarketingSourcesApi(unittest.TestCase):
    """MarketingSourcesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketingSourcesApi()

    def tearDown(self) -> None:
        pass

    def test_get_active_marketing_sources_api_v1_marketing_sources_get(self) -> None:
        """Test case for get_active_marketing_sources_api_v1_marketing_sources_get

        Get Active Marketing Sources
        """
        pass


if __name__ == '__main__':
    unittest.main()
