# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.api.orders_api import OrdersApi


class TestOrdersApi(unittest.TestCase):
    """OrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrdersApi()

    def tearDown(self) -> None:
        pass

    def test_change_order_status_api_v1_orders_uuid_status_post(self) -> None:
        """Test case for change_order_status_api_v1_orders_uuid_status_post

        Change Order Status
        """
        pass

    def test_create_order_api_v1_orders_post(self) -> None:
        """Test case for create_order_api_v1_orders_post

        Create Order
        """
        pass

    def test_delete_order_api_v1_orders_uuid_delete(self) -> None:
        """Test case for delete_order_api_v1_orders_uuid_delete

        Delete Order
        """
        pass

    def test_get_order_api_v1_orders_uuid_get(self) -> None:
        """Test case for get_order_api_v1_orders_uuid_get

        Get Order
        """
        pass

    def test_list_orders_api_v1_orders_get(self) -> None:
        """Test case for list_orders_api_v1_orders_get

        List Orders
        """
        pass


if __name__ == '__main__':
    unittest.main()
