# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.api.spam_admin_api import SpamAdminApi


class TestSpamAdminApi(unittest.TestCase):
    """SpamAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpamAdminApi()

    def tearDown(self) -> None:
        pass

    def test_admin_create_pattern_api_v1_admin_spam_patterns_post(self) -> None:
        """Test case for admin_create_pattern_api_v1_admin_spam_patterns_post

        Admin Create Pattern
        """
        pass

    def test_admin_delete_pattern_api_v1_admin_spam_patterns_uuid_delete(self) -> None:
        """Test case for admin_delete_pattern_api_v1_admin_spam_patterns_uuid_delete

        Admin Delete Pattern
        """
        pass

    def test_admin_event_stats_api_v1_admin_spam_events_stats_get(self) -> None:
        """Test case for admin_event_stats_api_v1_admin_spam_events_stats_get

        Admin Event Stats
        """
        pass

    def test_admin_list_events_api_v1_admin_spam_events_get(self) -> None:
        """Test case for admin_list_events_api_v1_admin_spam_events_get

        Admin List Events
        """
        pass

    def test_admin_list_patterns_api_v1_admin_spam_patterns_get(self) -> None:
        """Test case for admin_list_patterns_api_v1_admin_spam_patterns_get

        Admin List Patterns
        """
        pass

    def test_admin_mark_event_false_positive_api_v1_admin_spam_events_uuid_mark_false_positive_post(self) -> None:
        """Test case for admin_mark_event_false_positive_api_v1_admin_spam_events_uuid_mark_false_positive_post

        Admin Mark Event False Positive
        """
        pass

    def test_admin_update_pattern_api_v1_admin_spam_patterns_uuid_put(self) -> None:
        """Test case for admin_update_pattern_api_v1_admin_spam_patterns_uuid_put

        Admin Update Pattern
        """
        pass


if __name__ == '__main__':
    unittest.main()
