# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.contact_create import ContactCreate

class TestContactCreate(unittest.TestCase):
    """ContactCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactCreate:
        """Test ContactCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactCreate`
        """
        model = ContactCreate()
        if include_optional:
            return ContactCreate(
                first_name = '',
                last_name = '',
                contact_type = 'prospect',
                display_name = '',
                affiliations = [
                    clienthub.models.inline_affiliation_create.InlineAffiliationCreate(
                        organization_uuid = '', 
                        role_title = '', 
                        department = '', 
                        seniority = '', 
                        is_decision_maker = True, 
                        is_primary = True, 
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                phones = [
                    clienthub.models.contact_create_phone.ContactCreatePhone(
                        number = '', 
                        type = 'mobile', 
                        is_primary = True, 
                        affiliation_uuid = '', )
                    ],
                emails = [
                    clienthub.models.contact_create_email.ContactCreateEmail(
                        address = '', 
                        type = 'personal', 
                        is_primary = True, 
                        affiliation_uuid = '', )
                    ],
                marketing_sources = [
                    ''
                    ],
                data_source = '',
                external_refs_json = {
                    'key' : null
                    }
            )
        else:
            return ContactCreate(
                first_name = '',
                last_name = '',
        )
        """

    def testContactCreate(self):
        """Test ContactCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
