# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.contact_create_phone import ContactCreatePhone

class TestContactCreatePhone(unittest.TestCase):
    """ContactCreatePhone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactCreatePhone:
        """Test ContactCreatePhone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactCreatePhone`
        """
        model = ContactCreatePhone()
        if include_optional:
            return ContactCreatePhone(
                number = '',
                type = 'mobile',
                is_primary = True,
                affiliation_uuid = ''
            )
        else:
            return ContactCreatePhone(
                number = '',
        )
        """

    def testContactCreatePhone(self):
        """Test ContactCreatePhone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
