# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.lookup_match_email import LookupMatchEmail

class TestLookupMatchEmail(unittest.TestCase):
    """LookupMatchEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LookupMatchEmail:
        """Test LookupMatchEmail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LookupMatchEmail`
        """
        model = LookupMatchEmail()
        if include_optional:
            return LookupMatchEmail(
                address = '',
                type = '',
                is_primary = True,
                is_verified = True
            )
        else:
            return LookupMatchEmail(
                address = '',
                type = '',
                is_primary = True,
                is_verified = True,
        )
        """

    def testLookupMatchEmail(self):
        """Test LookupMatchEmail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
