# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.contact_update import ContactUpdate

class TestContactUpdate(unittest.TestCase):
    """ContactUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactUpdate:
        """Test ContactUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactUpdate`
        """
        model = ContactUpdate()
        if include_optional:
            return ContactUpdate(
                first_name = '',
                last_name = '',
                display_name = '',
                contact_type = '',
                enrichment_status = '',
                notes_text = '',
                external_refs_json = {
                    'key' : null
                    }
            )
        else:
            return ContactUpdate(
        )
        """

    def testContactUpdate(self):
        """Test ContactUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
