# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.lookup_match_channel_pref import LookupMatchChannelPref

class TestLookupMatchChannelPref(unittest.TestCase):
    """LookupMatchChannelPref unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LookupMatchChannelPref:
        """Test LookupMatchChannelPref
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LookupMatchChannelPref`
        """
        model = LookupMatchChannelPref()
        if include_optional:
            return LookupMatchChannelPref(
                preferred = True,
                opt_in = ''
            )
        else:
            return LookupMatchChannelPref(
                preferred = True,
        )
        """

    def testLookupMatchChannelPref(self):
        """Test LookupMatchChannelPref"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
