# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_chatwoot_webhook_api_v1_webhooks_chatwoot_post(self) -> None:
        """Test case for chatwoot_webhook_api_v1_webhooks_chatwoot_post

        Chatwoot Webhook
        """
        pass

    def test_invoiceninja_webhook_api_v1_webhooks_invoiceninja_post(self) -> None:
        """Test case for invoiceninja_webhook_api_v1_webhooks_invoiceninja_post

        Invoiceninja Webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
