# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.spam_pattern_update import SpamPatternUpdate

class TestSpamPatternUpdate(unittest.TestCase):
    """SpamPatternUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpamPatternUpdate:
        """Test SpamPatternUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpamPatternUpdate`
        """
        model = SpamPatternUpdate()
        if include_optional:
            return SpamPatternUpdate(
                pattern = '',
                notes = '',
                is_active = True
            )
        else:
            return SpamPatternUpdate(
        )
        """

    def testSpamPatternUpdate(self):
        """Test SpamPatternUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
