# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.marketing_opt_outs import MarketingOptOuts

class TestMarketingOptOuts(unittest.TestCase):
    """MarketingOptOuts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketingOptOuts:
        """Test MarketingOptOuts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketingOptOuts`
        """
        model = MarketingOptOuts()
        if include_optional:
            return MarketingOptOuts(
                opt_out_sms = True,
                opt_out_email = True,
                opt_out_phone = True
            )
        else:
            return MarketingOptOuts(
                opt_out_sms = True,
                opt_out_email = True,
                opt_out_phone = True,
        )
        """

    def testMarketingOptOuts(self):
        """Test MarketingOptOuts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
