# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.org_create import OrgCreate

class TestOrgCreate(unittest.TestCase):
    """OrgCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgCreate:
        """Test OrgCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgCreate`
        """
        model = OrgCreate()
        if include_optional:
            return OrgCreate(
                name = '',
                org_type = '',
                website = '',
                external_refs_json = {
                    'key' : null
                    }
            )
        else:
            return OrgCreate(
                name = '',
        )
        """

    def testOrgCreate(self):
        """Test OrgCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
