# coding: utf-8

"""
    Client Hub API

    Data-first customer intelligence microservice

    The version of the OpenAPI document: 0.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clienthub.models.affiliation_update import AffiliationUpdate

class TestAffiliationUpdate(unittest.TestCase):
    """AffiliationUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AffiliationUpdate:
        """Test AffiliationUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AffiliationUpdate`
        """
        model = AffiliationUpdate()
        if include_optional:
            return AffiliationUpdate(
                role_title = '',
                department = '',
                seniority = '',
                is_decision_maker = True,
                is_primary = True,
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                is_active = True,
                notes = '',
                external_refs_json = {
                    'key' : null
                    }
            )
        else:
            return AffiliationUpdate(
        )
        """

    def testAffiliationUpdate(self):
        """Test AffiliationUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
