/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffiliationCreate
 */
export interface AffiliationCreate {
    /**
     * 
     * @type {string}
     * @memberof AffiliationCreate
     */
    organizationUuid: string;
    /**
     * 
     * @type {string}
     * @memberof AffiliationCreate
     */
    roleTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliationCreate
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliationCreate
     */
    seniority?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AffiliationCreate
     */
    isDecisionMaker?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AffiliationCreate
     */
    isPrimary?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AffiliationCreate
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AffiliationCreate
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliationCreate
     */
    notes?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AffiliationCreate
     */
    externalRefsJson?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the AffiliationCreate interface.
 */
export function instanceOfAffiliationCreate(value: object): value is AffiliationCreate {
    if (!('organizationUuid' in value) || value['organizationUuid'] === undefined) return false;
    return true;
}

export function AffiliationCreateFromJSON(json: any): AffiliationCreate {
    return AffiliationCreateFromJSONTyped(json, false);
}

export function AffiliationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffiliationCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationUuid': json['organization_uuid'],
        'roleTitle': json['role_title'] == null ? undefined : json['role_title'],
        'department': json['department'] == null ? undefined : json['department'],
        'seniority': json['seniority'] == null ? undefined : json['seniority'],
        'isDecisionMaker': json['is_decision_maker'] == null ? undefined : json['is_decision_maker'],
        'isPrimary': json['is_primary'] == null ? undefined : json['is_primary'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'externalRefsJson': json['external_refs_json'] == null ? undefined : json['external_refs_json'],
    };
}

export function AffiliationCreateToJSON(json: any): AffiliationCreate {
    return AffiliationCreateToJSONTyped(json, false);
}

export function AffiliationCreateToJSONTyped(value?: AffiliationCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_uuid': value['organizationUuid'],
        'role_title': value['roleTitle'],
        'department': value['department'],
        'seniority': value['seniority'],
        'is_decision_maker': value['isDecisionMaker'],
        'is_primary': value['isPrimary'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString().substring(0,10)),
        'notes': value['notes'],
        'external_refs_json': value['externalRefsJson'],
    };
}

