/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AffiliationUpdate
 */
export interface AffiliationUpdate {
    /**
     * 
     * @type {string}
     * @memberof AffiliationUpdate
     */
    roleTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliationUpdate
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliationUpdate
     */
    seniority?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AffiliationUpdate
     */
    isDecisionMaker?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof AffiliationUpdate
     */
    isPrimary?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof AffiliationUpdate
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AffiliationUpdate
     */
    endDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof AffiliationUpdate
     */
    isActive?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AffiliationUpdate
     */
    notes?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AffiliationUpdate
     */
    externalRefsJson?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the AffiliationUpdate interface.
 */
export function instanceOfAffiliationUpdate(value: object): value is AffiliationUpdate {
    return true;
}

export function AffiliationUpdateFromJSON(json: any): AffiliationUpdate {
    return AffiliationUpdateFromJSONTyped(json, false);
}

export function AffiliationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AffiliationUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'roleTitle': json['role_title'] == null ? undefined : json['role_title'],
        'department': json['department'] == null ? undefined : json['department'],
        'seniority': json['seniority'] == null ? undefined : json['seniority'],
        'isDecisionMaker': json['is_decision_maker'] == null ? undefined : json['is_decision_maker'],
        'isPrimary': json['is_primary'] == null ? undefined : json['is_primary'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'externalRefsJson': json['external_refs_json'] == null ? undefined : json['external_refs_json'],
    };
}

export function AffiliationUpdateToJSON(json: any): AffiliationUpdate {
    return AffiliationUpdateToJSONTyped(json, false);
}

export function AffiliationUpdateToJSONTyped(value?: AffiliationUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role_title': value['roleTitle'],
        'department': value['department'],
        'seniority': value['seniority'],
        'is_decision_maker': value['isDecisionMaker'],
        'is_primary': value['isPrimary'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate'] as any).toISOString().substring(0,10)),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate'] as any).toISOString().substring(0,10)),
        'is_active': value['isActive'],
        'notes': value['notes'],
        'external_refs_json': value['externalRefsJson'],
    };
}

