/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaxAmount } from './TaxAmount';
import {
    TaxAmountFromJSON,
    TaxAmountFromJSONTyped,
    TaxAmountToJSON,
    TaxAmountToJSONTyped,
} from './TaxAmount';
import type { Subtotal } from './Subtotal';
import {
    SubtotalFromJSON,
    SubtotalFromJSONTyped,
    SubtotalToJSON,
    SubtotalToJSONTyped,
} from './Subtotal';

/**
 * 
 * @export
 * @interface InvoiceCreate
 */
export interface InvoiceCreate {
    /**
     * 
     * @type {string}
     * @memberof InvoiceCreate
     */
    orderUuid: string;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceCreate
     */
    invoiceDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceCreate
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {Subtotal}
     * @memberof InvoiceCreate
     */
    subtotal: Subtotal;
    /**
     * 
     * @type {TaxAmount}
     * @memberof InvoiceCreate
     */
    taxAmount?: TaxAmount;
}

/**
 * Check if a given object implements the InvoiceCreate interface.
 */
export function instanceOfInvoiceCreate(value: object): value is InvoiceCreate {
    if (!('orderUuid' in value) || value['orderUuid'] === undefined) return false;
    if (!('invoiceDate' in value) || value['invoiceDate'] === undefined) return false;
    if (!('subtotal' in value) || value['subtotal'] === undefined) return false;
    return true;
}

export function InvoiceCreateFromJSON(json: any): InvoiceCreate {
    return InvoiceCreateFromJSONTyped(json, false);
}

export function InvoiceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'orderUuid': json['order_uuid'],
        'invoiceDate': (new Date(json['invoice_date'])),
        'dueDate': json['due_date'] == null ? undefined : (new Date(json['due_date'])),
        'subtotal': SubtotalFromJSON(json['subtotal']),
        'taxAmount': json['tax_amount'] == null ? undefined : TaxAmountFromJSON(json['tax_amount']),
    };
}

export function InvoiceCreateToJSON(json: any): InvoiceCreate {
    return InvoiceCreateToJSONTyped(json, false);
}

export function InvoiceCreateToJSONTyped(value?: InvoiceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_uuid': value['orderUuid'],
        'invoice_date': ((value['invoiceDate']).toISOString().substring(0,10)),
        'due_date': value['dueDate'] == null ? undefined : ((value['dueDate'] as any).toISOString().substring(0,10)),
        'subtotal': SubtotalToJSON(value['subtotal']),
        'tax_amount': TaxAmountToJSON(value['taxAmount']),
    };
}

