/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LookupMatchChannelPref
 */
export interface LookupMatchChannelPref {
    /**
     * 
     * @type {boolean}
     * @memberof LookupMatchChannelPref
     */
    preferred: boolean;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchChannelPref
     */
    optIn?: string | null;
}

/**
 * Check if a given object implements the LookupMatchChannelPref interface.
 */
export function instanceOfLookupMatchChannelPref(value: object): value is LookupMatchChannelPref {
    if (!('preferred' in value) || value['preferred'] === undefined) return false;
    return true;
}

export function LookupMatchChannelPrefFromJSON(json: any): LookupMatchChannelPref {
    return LookupMatchChannelPrefFromJSONTyped(json, false);
}

export function LookupMatchChannelPrefFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupMatchChannelPref {
    if (json == null) {
        return json;
    }
    return {
        
        'preferred': json['preferred'],
        'optIn': json['opt_in'] == null ? undefined : json['opt_in'],
    };
}

export function LookupMatchChannelPrefToJSON(json: any): LookupMatchChannelPref {
    return LookupMatchChannelPrefToJSONTyped(json, false);
}

export function LookupMatchChannelPrefToJSONTyped(value?: LookupMatchChannelPref | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preferred': value['preferred'],
        'opt_in': value['optIn'],
    };
}

