/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LookupMatchEmail
 */
export interface LookupMatchEmail {
    /**
     * 
     * @type {string}
     * @memberof LookupMatchEmail
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchEmail
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof LookupMatchEmail
     */
    isPrimary: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LookupMatchEmail
     */
    isVerified: boolean;
}

/**
 * Check if a given object implements the LookupMatchEmail interface.
 */
export function instanceOfLookupMatchEmail(value: object): value is LookupMatchEmail {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isPrimary' in value) || value['isPrimary'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    return true;
}

export function LookupMatchEmailFromJSON(json: any): LookupMatchEmail {
    return LookupMatchEmailFromJSONTyped(json, false);
}

export function LookupMatchEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupMatchEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'type': json['type'],
        'isPrimary': json['is_primary'],
        'isVerified': json['is_verified'],
    };
}

export function LookupMatchEmailToJSON(json: any): LookupMatchEmail {
    return LookupMatchEmailToJSONTyped(json, false);
}

export function LookupMatchEmailToJSONTyped(value?: LookupMatchEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'type': value['type'],
        'is_primary': value['isPrimary'],
        'is_verified': value['isVerified'],
    };
}

