/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LookupMatchCommunication
 */
export interface LookupMatchCommunication {
    /**
     * 
     * @type {string}
     * @memberof LookupMatchCommunication
     */
    channel: string;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchCommunication
     */
    direction: string;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchCommunication
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchCommunication
     */
    occurredAt?: string | null;
}

/**
 * Check if a given object implements the LookupMatchCommunication interface.
 */
export function instanceOfLookupMatchCommunication(value: object): value is LookupMatchCommunication {
    if (!('channel' in value) || value['channel'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    return true;
}

export function LookupMatchCommunicationFromJSON(json: any): LookupMatchCommunication {
    return LookupMatchCommunicationFromJSONTyped(json, false);
}

export function LookupMatchCommunicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupMatchCommunication {
    if (json == null) {
        return json;
    }
    return {
        
        'channel': json['channel'],
        'direction': json['direction'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'occurredAt': json['occurred_at'] == null ? undefined : json['occurred_at'],
    };
}

export function LookupMatchCommunicationToJSON(json: any): LookupMatchCommunication {
    return LookupMatchCommunicationToJSONTyped(json, false);
}

export function LookupMatchCommunicationToJSONTyped(value?: LookupMatchCommunication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel': value['channel'],
        'direction': value['direction'],
        'subject': value['subject'],
        'occurred_at': value['occurredAt'],
    };
}

