/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LookupMatchPhone
 */
export interface LookupMatchPhone {
    /**
     * 
     * @type {string}
     * @memberof LookupMatchPhone
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchPhone
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof LookupMatchPhone
     */
    isPrimary: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LookupMatchPhone
     */
    isVerified: boolean;
}

/**
 * Check if a given object implements the LookupMatchPhone interface.
 */
export function instanceOfLookupMatchPhone(value: object): value is LookupMatchPhone {
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('isPrimary' in value) || value['isPrimary'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    return true;
}

export function LookupMatchPhoneFromJSON(json: any): LookupMatchPhone {
    return LookupMatchPhoneFromJSONTyped(json, false);
}

export function LookupMatchPhoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupMatchPhone {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'],
        'type': json['type'],
        'isPrimary': json['is_primary'],
        'isVerified': json['is_verified'],
    };
}

export function LookupMatchPhoneToJSON(json: any): LookupMatchPhone {
    return LookupMatchPhoneToJSONTyped(json, false);
}

export function LookupMatchPhoneToJSONTyped(value?: LookupMatchPhone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'type': value['type'],
        'is_primary': value['isPrimary'],
        'is_verified': value['isVerified'],
    };
}

