/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LookupMatchOrder
 */
export interface LookupMatchOrder {
    /**
     * 
     * @type {string}
     * @memberof LookupMatchOrder
     */
    orderNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchOrder
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchOrder
     */
    total: string;
    /**
     * 
     * @type {string}
     * @memberof LookupMatchOrder
     */
    orderDate: string;
}

/**
 * Check if a given object implements the LookupMatchOrder interface.
 */
export function instanceOfLookupMatchOrder(value: object): value is LookupMatchOrder {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('orderDate' in value) || value['orderDate'] === undefined) return false;
    return true;
}

export function LookupMatchOrderFromJSON(json: any): LookupMatchOrder {
    return LookupMatchOrderFromJSONTyped(json, false);
}

export function LookupMatchOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupMatchOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'orderNumber': json['order_number'] == null ? undefined : json['order_number'],
        'status': json['status'],
        'total': json['total'],
        'orderDate': json['order_date'],
    };
}

export function LookupMatchOrderToJSON(json: any): LookupMatchOrder {
    return LookupMatchOrderToJSONTyped(json, false);
}

export function LookupMatchOrderToJSONTyped(value?: LookupMatchOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_number': value['orderNumber'],
        'status': value['status'],
        'total': value['total'],
        'order_date': value['orderDate'],
    };
}

