/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarketingOptOuts
 */
export interface MarketingOptOuts {
    /**
     * 
     * @type {boolean}
     * @memberof MarketingOptOuts
     */
    optOutSms: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarketingOptOuts
     */
    optOutEmail: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarketingOptOuts
     */
    optOutPhone: boolean;
}

/**
 * Check if a given object implements the MarketingOptOuts interface.
 */
export function instanceOfMarketingOptOuts(value: object): value is MarketingOptOuts {
    if (!('optOutSms' in value) || value['optOutSms'] === undefined) return false;
    if (!('optOutEmail' in value) || value['optOutEmail'] === undefined) return false;
    if (!('optOutPhone' in value) || value['optOutPhone'] === undefined) return false;
    return true;
}

export function MarketingOptOutsFromJSON(json: any): MarketingOptOuts {
    return MarketingOptOutsFromJSONTyped(json, false);
}

export function MarketingOptOutsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingOptOuts {
    if (json == null) {
        return json;
    }
    return {
        
        'optOutSms': json['opt_out_sms'],
        'optOutEmail': json['opt_out_email'],
        'optOutPhone': json['opt_out_phone'],
    };
}

export function MarketingOptOutsToJSON(json: any): MarketingOptOuts {
    return MarketingOptOutsToJSONTyped(json, false);
}

export function MarketingOptOutsToJSONTyped(value?: MarketingOptOuts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'opt_out_sms': value['optOutSms'],
        'opt_out_email': value['optOutEmail'],
        'opt_out_phone': value['optOutPhone'],
    };
}

