/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreferenceSet
 */
export interface PreferenceSet {
    /**
     * 
     * @type {string}
     * @memberof PreferenceSet
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof PreferenceSet
     */
    dataSource?: string | null;
}

/**
 * Check if a given object implements the PreferenceSet interface.
 */
export function instanceOfPreferenceSet(value: object): value is PreferenceSet {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function PreferenceSetFromJSON(json: any): PreferenceSet {
    return PreferenceSetFromJSONTyped(json, false);
}

export function PreferenceSetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferenceSet {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'dataSource': json['data_source'] == null ? undefined : json['data_source'],
    };
}

export function PreferenceSetToJSON(json: any): PreferenceSet {
    return PreferenceSetToJSONTyped(json, false);
}

export function PreferenceSetToJSONTyped(value?: PreferenceSet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'data_source': value['dataSource'],
    };
}

