/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceUpdate
 */
export interface SourceUpdate {
    /**
     * 
     * @type {string}
     * @memberof SourceUpdate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceUpdate
     */
    sourceType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceUpdate
     */
    domain?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceUpdate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the SourceUpdate interface.
 */
export function instanceOfSourceUpdate(value: object): value is SourceUpdate {
    return true;
}

export function SourceUpdateFromJSON(json: any): SourceUpdate {
    return SourceUpdateFromJSONTyped(json, false);
}

export function SourceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'sourceType': json['source_type'] == null ? undefined : json['source_type'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function SourceUpdateToJSON(json: any): SourceUpdate {
    return SourceUpdateToJSONTyped(json, false);
}

export function SourceUpdateToJSONTyped(value?: SourceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'source_type': value['sourceType'],
        'domain': value['domain'],
        'description': value['description'],
    };
}

