/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceCreate
 */
export interface SourceCreate {
    /**
     * 
     * @type {string}
     * @memberof SourceCreate
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCreate
     */
    sourceType?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCreate
     */
    domain?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceCreate
     */
    description?: string | null;
}

/**
 * Check if a given object implements the SourceCreate interface.
 */
export function instanceOfSourceCreate(value: object): value is SourceCreate {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SourceCreateFromJSON(json: any): SourceCreate {
    return SourceCreateFromJSONTyped(json, false);
}

export function SourceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
        'sourceType': json['source_type'] == null ? undefined : json['source_type'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function SourceCreateToJSON(json: any): SourceCreate {
    return SourceCreateToJSONTyped(json, false);
}

export function SourceCreateToJSONTyped(value?: SourceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'source_type': value['sourceType'],
        'domain': value['domain'],
        'description': value['description'],
    };
}

