/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiKeyCreate,
  HTTPValidationError,
  SourceCreate,
  SourceUpdate,
} from '../models/index';
import {
    ApiKeyCreateFromJSON,
    ApiKeyCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SourceCreateFromJSON,
    SourceCreateToJSON,
    SourceUpdateFromJSON,
    SourceUpdateToJSON,
} from '../models/index';

export interface CreateApiKeyApiV1AdminSourcesUuidApiKeysPostRequest {
    uuid: string;
    apiKeyCreate: ApiKeyCreate;
}

export interface CreateSourceApiV1AdminSourcesPostRequest {
    sourceCreate: SourceCreate;
}

export interface DeleteSourceApiV1AdminSourcesUuidDeleteRequest {
    uuid: string;
}

export interface GetSourceApiV1AdminSourcesUuidGetRequest {
    uuid: string;
}

export interface ListApiKeysApiV1AdminSourcesUuidApiKeysGetRequest {
    uuid: string;
}

export interface ListEventsApiV1AdminEventsGetRequest {
    sourceCode?: string | null;
    channelCode?: string | null;
    dateFrom?: string | null;
    dateTo?: string | null;
    limit?: number;
}

export interface RevokeApiKeyApiV1AdminApiKeysUuidDeleteRequest {
    uuid: string;
}

export interface UpdateSourceApiV1AdminSourcesUuidPutRequest {
    uuid: string;
    sourceUpdate: SourceUpdate;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Create Api Key
     */
    async createApiKeyApiV1AdminSourcesUuidApiKeysPostRaw(requestParameters: CreateApiKeyApiV1AdminSourcesUuidApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling createApiKeyApiV1AdminSourcesUuidApiKeysPost().'
            );
        }

        if (requestParameters['apiKeyCreate'] == null) {
            throw new runtime.RequiredError(
                'apiKeyCreate',
                'Required parameter "apiKeyCreate" was null or undefined when calling createApiKeyApiV1AdminSourcesUuidApiKeysPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/sources/{uuid}/api-keys`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiKeyCreateToJSON(requestParameters['apiKeyCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Api Key
     */
    async createApiKeyApiV1AdminSourcesUuidApiKeysPost(requestParameters: CreateApiKeyApiV1AdminSourcesUuidApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createApiKeyApiV1AdminSourcesUuidApiKeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Source
     */
    async createSourceApiV1AdminSourcesPostRaw(requestParameters: CreateSourceApiV1AdminSourcesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sourceCreate'] == null) {
            throw new runtime.RequiredError(
                'sourceCreate',
                'Required parameter "sourceCreate" was null or undefined when calling createSourceApiV1AdminSourcesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/sources`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SourceCreateToJSON(requestParameters['sourceCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Source
     */
    async createSourceApiV1AdminSourcesPost(requestParameters: CreateSourceApiV1AdminSourcesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createSourceApiV1AdminSourcesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Source
     */
    async deleteSourceApiV1AdminSourcesUuidDeleteRaw(requestParameters: DeleteSourceApiV1AdminSourcesUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling deleteSourceApiV1AdminSourcesUuidDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/sources/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Source
     */
    async deleteSourceApiV1AdminSourcesUuidDelete(requestParameters: DeleteSourceApiV1AdminSourcesUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSourceApiV1AdminSourcesUuidDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Source
     */
    async getSourceApiV1AdminSourcesUuidGetRaw(requestParameters: GetSourceApiV1AdminSourcesUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getSourceApiV1AdminSourcesUuidGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/sources/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Source
     */
    async getSourceApiV1AdminSourcesUuidGet(requestParameters: GetSourceApiV1AdminSourcesUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSourceApiV1AdminSourcesUuidGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Api Keys
     */
    async listApiKeysApiV1AdminSourcesUuidApiKeysGetRaw(requestParameters: ListApiKeysApiV1AdminSourcesUuidApiKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling listApiKeysApiV1AdminSourcesUuidApiKeysGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/sources/{uuid}/api-keys`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Api Keys
     */
    async listApiKeysApiV1AdminSourcesUuidApiKeysGet(requestParameters: ListApiKeysApiV1AdminSourcesUuidApiKeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listApiKeysApiV1AdminSourcesUuidApiKeysGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Events
     */
    async listEventsApiV1AdminEventsGetRaw(requestParameters: ListEventsApiV1AdminEventsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['sourceCode'] != null) {
            queryParameters['source_code'] = requestParameters['sourceCode'];
        }

        if (requestParameters['channelCode'] != null) {
            queryParameters['channel_code'] = requestParameters['channelCode'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = requestParameters['dateFrom'];
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = requestParameters['dateTo'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Events
     */
    async listEventsApiV1AdminEventsGet(requestParameters: ListEventsApiV1AdminEventsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listEventsApiV1AdminEventsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Sources
     */
    async listSourcesApiV1AdminSourcesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/sources`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Sources
     */
    async listSourcesApiV1AdminSourcesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listSourcesApiV1AdminSourcesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Revoke Api Key
     */
    async revokeApiKeyApiV1AdminApiKeysUuidDeleteRaw(requestParameters: RevokeApiKeyApiV1AdminApiKeysUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling revokeApiKeyApiV1AdminApiKeysUuidDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/api-keys/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Revoke Api Key
     */
    async revokeApiKeyApiV1AdminApiKeysUuidDelete(requestParameters: RevokeApiKeyApiV1AdminApiKeysUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.revokeApiKeyApiV1AdminApiKeysUuidDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Update Source
     */
    async updateSourceApiV1AdminSourcesUuidPutRaw(requestParameters: UpdateSourceApiV1AdminSourcesUuidPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling updateSourceApiV1AdminSourcesUuidPut().'
            );
        }

        if (requestParameters['sourceUpdate'] == null) {
            throw new runtime.RequiredError(
                'sourceUpdate',
                'Required parameter "sourceUpdate" was null or undefined when calling updateSourceApiV1AdminSourcesUuidPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/sources/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SourceUpdateToJSON(requestParameters['sourceUpdate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Update Source
     */
    async updateSourceApiV1AdminSourcesUuidPut(requestParameters: UpdateSourceApiV1AdminSourcesUuidPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.updateSourceApiV1AdminSourcesUuidPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
