/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommCreate,
  HTTPValidationError,
} from '../models/index';
import {
    CommCreateFromJSON,
    CommCreateToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateCommunicationApiV1CommunicationsPostRequest {
    commCreate: CommCreate;
}

export interface GetCommunicationApiV1CommunicationsUuidGetRequest {
    uuid: string;
}

export interface ListCommunicationsApiV1CommunicationsGetRequest {
    page?: number;
    perPage?: number;
    contactUuid?: string | null;
    channel?: string | null;
    direction?: string | null;
}

/**
 * 
 */
export class CommunicationsApi extends runtime.BaseAPI {

    /**
     * Create Communication
     */
    async createCommunicationApiV1CommunicationsPostRaw(requestParameters: CreateCommunicationApiV1CommunicationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['commCreate'] == null) {
            throw new runtime.RequiredError(
                'commCreate',
                'Required parameter "commCreate" was null or undefined when calling createCommunicationApiV1CommunicationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/communications`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommCreateToJSON(requestParameters['commCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Communication
     */
    async createCommunicationApiV1CommunicationsPost(requestParameters: CreateCommunicationApiV1CommunicationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createCommunicationApiV1CommunicationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Communication
     */
    async getCommunicationApiV1CommunicationsUuidGetRaw(requestParameters: GetCommunicationApiV1CommunicationsUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getCommunicationApiV1CommunicationsUuidGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/communications/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Communication
     */
    async getCommunicationApiV1CommunicationsUuidGet(requestParameters: GetCommunicationApiV1CommunicationsUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getCommunicationApiV1CommunicationsUuidGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Communications
     */
    async listCommunicationsApiV1CommunicationsGetRaw(requestParameters: ListCommunicationsApiV1CommunicationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['contactUuid'] != null) {
            queryParameters['contact_uuid'] = requestParameters['contactUuid'];
        }

        if (requestParameters['channel'] != null) {
            queryParameters['channel'] = requestParameters['channel'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/communications`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Communications
     */
    async listCommunicationsApiV1CommunicationsGet(requestParameters: ListCommunicationsApiV1CommunicationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listCommunicationsApiV1CommunicationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
