/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  OrderCreate,
  StatusChange,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OrderCreateFromJSON,
    OrderCreateToJSON,
    StatusChangeFromJSON,
    StatusChangeToJSON,
} from '../models/index';

export interface ChangeOrderStatusApiV1OrdersUuidStatusPostRequest {
    uuid: string;
    statusChange: StatusChange;
}

export interface CreateOrderApiV1OrdersPostRequest {
    orderCreate: OrderCreate;
}

export interface DeleteOrderApiV1OrdersUuidDeleteRequest {
    uuid: string;
}

export interface GetOrderApiV1OrdersUuidGetRequest {
    uuid: string;
}

export interface ListOrdersApiV1OrdersGetRequest {
    page?: number;
    perPage?: number;
    status?: string | null;
    contactUuid?: string | null;
}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI {

    /**
     * Change Order Status
     */
    async changeOrderStatusApiV1OrdersUuidStatusPostRaw(requestParameters: ChangeOrderStatusApiV1OrdersUuidStatusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling changeOrderStatusApiV1OrdersUuidStatusPost().'
            );
        }

        if (requestParameters['statusChange'] == null) {
            throw new runtime.RequiredError(
                'statusChange',
                'Required parameter "statusChange" was null or undefined when calling changeOrderStatusApiV1OrdersUuidStatusPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/orders/{uuid}/status`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StatusChangeToJSON(requestParameters['statusChange']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Change Order Status
     */
    async changeOrderStatusApiV1OrdersUuidStatusPost(requestParameters: ChangeOrderStatusApiV1OrdersUuidStatusPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.changeOrderStatusApiV1OrdersUuidStatusPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Order
     */
    async createOrderApiV1OrdersPostRaw(requestParameters: CreateOrderApiV1OrdersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['orderCreate'] == null) {
            throw new runtime.RequiredError(
                'orderCreate',
                'Required parameter "orderCreate" was null or undefined when calling createOrderApiV1OrdersPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/orders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderCreateToJSON(requestParameters['orderCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Create Order
     */
    async createOrderApiV1OrdersPost(requestParameters: CreateOrderApiV1OrdersPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createOrderApiV1OrdersPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Order
     */
    async deleteOrderApiV1OrdersUuidDeleteRaw(requestParameters: DeleteOrderApiV1OrdersUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling deleteOrderApiV1OrdersUuidDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/orders/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Order
     */
    async deleteOrderApiV1OrdersUuidDelete(requestParameters: DeleteOrderApiV1OrdersUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteOrderApiV1OrdersUuidDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get Order
     */
    async getOrderApiV1OrdersUuidGetRaw(requestParameters: GetOrderApiV1OrdersUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getOrderApiV1OrdersUuidGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/orders/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Order
     */
    async getOrderApiV1OrdersUuidGet(requestParameters: GetOrderApiV1OrdersUuidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getOrderApiV1OrdersUuidGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Orders
     */
    async listOrdersApiV1OrdersGetRaw(requestParameters: ListOrdersApiV1OrdersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['contactUuid'] != null) {
            queryParameters['contact_uuid'] = requestParameters['contactUuid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List Orders
     */
    async listOrdersApiV1OrdersGet(requestParameters: ListOrdersApiV1OrdersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listOrdersApiV1OrdersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
