/* tslint:disable */
/* eslint-disable */
/**
 * Client Hub API
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SpamPatternCreate,
  SpamPatternUpdate,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SpamPatternCreateFromJSON,
    SpamPatternCreateToJSON,
    SpamPatternUpdateFromJSON,
    SpamPatternUpdateToJSON,
} from '../models/index';

export interface AdminCreatePatternApiV1AdminSpamPatternsPostRequest {
    spamPatternCreate: SpamPatternCreate;
}

export interface AdminDeletePatternApiV1AdminSpamPatternsUuidDeleteRequest {
    uuid: string;
}

export interface AdminListEventsApiV1AdminSpamEventsGetRequest {
    page?: number;
    perPage?: number;
    endpoint?: string | null;
    integrationKind?: string | null;
    rejectionReason?: string | null;
    submittedEmail?: string | null;
    wasFalsePositive?: boolean | null;
}

export interface AdminListPatternsApiV1AdminSpamPatternsGetRequest {
    page?: number;
    perPage?: number;
    isActive?: boolean | null;
    patternKind?: string | null;
}

export interface AdminMarkEventFalsePositiveApiV1AdminSpamEventsUuidMarkFalsePositivePostRequest {
    uuid: string;
}

export interface AdminUpdatePatternApiV1AdminSpamPatternsUuidPutRequest {
    uuid: string;
    spamPatternUpdate: SpamPatternUpdate;
}

/**
 * 
 */
export class SpamAdminApi extends runtime.BaseAPI {

    /**
     * Admin Create Pattern
     */
    async adminCreatePatternApiV1AdminSpamPatternsPostRaw(requestParameters: AdminCreatePatternApiV1AdminSpamPatternsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['spamPatternCreate'] == null) {
            throw new runtime.RequiredError(
                'spamPatternCreate',
                'Required parameter "spamPatternCreate" was null or undefined when calling adminCreatePatternApiV1AdminSpamPatternsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/spam-patterns`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SpamPatternCreateToJSON(requestParameters['spamPatternCreate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Admin Create Pattern
     */
    async adminCreatePatternApiV1AdminSpamPatternsPost(requestParameters: AdminCreatePatternApiV1AdminSpamPatternsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.adminCreatePatternApiV1AdminSpamPatternsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Admin Delete Pattern
     */
    async adminDeletePatternApiV1AdminSpamPatternsUuidDeleteRaw(requestParameters: AdminDeletePatternApiV1AdminSpamPatternsUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling adminDeletePatternApiV1AdminSpamPatternsUuidDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/spam-patterns/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Admin Delete Pattern
     */
    async adminDeletePatternApiV1AdminSpamPatternsUuidDelete(requestParameters: AdminDeletePatternApiV1AdminSpamPatternsUuidDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminDeletePatternApiV1AdminSpamPatternsUuidDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Admin Event Stats
     */
    async adminEventStatsApiV1AdminSpamEventsStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/spam-events/stats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Admin Event Stats
     */
    async adminEventStatsApiV1AdminSpamEventsStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.adminEventStatsApiV1AdminSpamEventsStatsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Admin List Events
     */
    async adminListEventsApiV1AdminSpamEventsGetRaw(requestParameters: AdminListEventsApiV1AdminSpamEventsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['endpoint'] != null) {
            queryParameters['endpoint'] = requestParameters['endpoint'];
        }

        if (requestParameters['integrationKind'] != null) {
            queryParameters['integration_kind'] = requestParameters['integrationKind'];
        }

        if (requestParameters['rejectionReason'] != null) {
            queryParameters['rejection_reason'] = requestParameters['rejectionReason'];
        }

        if (requestParameters['submittedEmail'] != null) {
            queryParameters['submitted_email'] = requestParameters['submittedEmail'];
        }

        if (requestParameters['wasFalsePositive'] != null) {
            queryParameters['was_false_positive'] = requestParameters['wasFalsePositive'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/spam-events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Admin List Events
     */
    async adminListEventsApiV1AdminSpamEventsGet(requestParameters: AdminListEventsApiV1AdminSpamEventsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.adminListEventsApiV1AdminSpamEventsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Admin List Patterns
     */
    async adminListPatternsApiV1AdminSpamPatternsGetRaw(requestParameters: AdminListPatternsApiV1AdminSpamPatternsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['isActive'] != null) {
            queryParameters['is_active'] = requestParameters['isActive'];
        }

        if (requestParameters['patternKind'] != null) {
            queryParameters['pattern_kind'] = requestParameters['patternKind'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/spam-patterns`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Admin List Patterns
     */
    async adminListPatternsApiV1AdminSpamPatternsGet(requestParameters: AdminListPatternsApiV1AdminSpamPatternsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.adminListPatternsApiV1AdminSpamPatternsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Admin Mark Event False Positive
     */
    async adminMarkEventFalsePositiveApiV1AdminSpamEventsUuidMarkFalsePositivePostRaw(requestParameters: AdminMarkEventFalsePositiveApiV1AdminSpamEventsUuidMarkFalsePositivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling adminMarkEventFalsePositiveApiV1AdminSpamEventsUuidMarkFalsePositivePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/spam-events/{uuid}/mark-false-positive`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Admin Mark Event False Positive
     */
    async adminMarkEventFalsePositiveApiV1AdminSpamEventsUuidMarkFalsePositivePost(requestParameters: AdminMarkEventFalsePositiveApiV1AdminSpamEventsUuidMarkFalsePositivePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.adminMarkEventFalsePositiveApiV1AdminSpamEventsUuidMarkFalsePositivePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Admin Update Pattern
     */
    async adminUpdatePatternApiV1AdminSpamPatternsUuidPutRaw(requestParameters: AdminUpdatePatternApiV1AdminSpamPatternsUuidPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling adminUpdatePatternApiV1AdminSpamPatternsUuidPut().'
            );
        }

        if (requestParameters['spamPatternUpdate'] == null) {
            throw new runtime.RequiredError(
                'spamPatternUpdate',
                'Required parameter "spamPatternUpdate" was null or undefined when calling adminUpdatePatternApiV1AdminSpamPatternsUuidPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }

        const response = await this.request({
            path: `/api/v1/admin/spam-patterns/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SpamPatternUpdateToJSON(requestParameters['spamPatternUpdate']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Admin Update Pattern
     */
    async adminUpdatePatternApiV1AdminSpamPatternsUuidPut(requestParameters: AdminUpdatePatternApiV1AdminSpamPatternsUuidPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.adminUpdatePatternApiV1AdminSpamPatternsUuidPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
