<?php
/**
 * AffiliationsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Client Hub API
 *
 * Data-first customer intelligence microservice
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClientHub\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ClientHub\ApiException;
use ClientHub\Configuration;
use ClientHub\HeaderSelector;
use ClientHub\ObjectSerializer;

/**
 * AffiliationsApi Class Doc Comment
 *
 * @category Class
 * @package  ClientHub
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AffiliationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost' => [
            'application/json',
        ],
        'deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete' => [
            'application/json',
        ],
        'listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet' => [
            'application/json',
        ],
        'updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost
     *
     * Create Affiliation Endpoint
     *
     * @param  string $contact_uuid contact_uuid (required)
     * @param  \ClientHub\Model\AffiliationCreate $affiliation_create affiliation_create (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\ClientHub\Model\HTTPValidationError
     */
    public function createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost($contact_uuid, $affiliation_create, string $contentType = self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'][0])
    {
        list($response) = $this->createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostWithHttpInfo($contact_uuid, $affiliation_create, $contentType);
        return $response;
    }

    /**
     * Operation createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostWithHttpInfo
     *
     * Create Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  \ClientHub\Model\AffiliationCreate $affiliation_create (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\ClientHub\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostWithHttpInfo($contact_uuid, $affiliation_create, string $contentType = self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'][0])
    {
        $request = $this->createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostRequest($contact_uuid, $affiliation_create, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\ClientHub\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ClientHub\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ClientHub\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientHub\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostAsync
     *
     * Create Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  \ClientHub\Model\AffiliationCreate $affiliation_create (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostAsync($contact_uuid, $affiliation_create, string $contentType = self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'][0])
    {
        return $this->createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostAsyncWithHttpInfo($contact_uuid, $affiliation_create, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostAsyncWithHttpInfo
     *
     * Create Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  \ClientHub\Model\AffiliationCreate $affiliation_create (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostAsyncWithHttpInfo($contact_uuid, $affiliation_create, string $contentType = self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'][0])
    {
        $returnType = 'mixed';
        $request = $this->createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostRequest($contact_uuid, $affiliation_create, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'
     *
     * @param  string $contact_uuid (required)
     * @param  \ClientHub\Model\AffiliationCreate $affiliation_create (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPostRequest($contact_uuid, $affiliation_create, string $contentType = self::contentTypes['createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'][0])
    {

        // verify the required parameter 'contact_uuid' is set
        if ($contact_uuid === null || (is_array($contact_uuid) && count($contact_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contact_uuid when calling createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'
            );
        }

        // verify the required parameter 'affiliation_create' is set
        if ($affiliation_create === null || (is_array($affiliation_create) && count($affiliation_create) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $affiliation_create when calling createAffiliationEndpointApiV1ContactsContactUuidAffiliationsPost'
            );
        }


        $resourcePath = '/api/v1/contacts/{contact_uuid}/affiliations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contact_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'contact_uuid' . '}',
                ObjectSerializer::toPathValue($contact_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($affiliation_create)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($affiliation_create));
            } else {
                $httpBody = $affiliation_create;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete
     *
     * Delete Affiliation Endpoint
     *
     * @param  string $contact_uuid contact_uuid (required)
     * @param  string $affiliation_uuid affiliation_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete($contact_uuid, $affiliation_uuid, string $contentType = self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'][0])
    {
        $this->deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteWithHttpInfo($contact_uuid, $affiliation_uuid, $contentType);
    }

    /**
     * Operation deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteWithHttpInfo
     *
     * Delete Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteWithHttpInfo($contact_uuid, $affiliation_uuid, string $contentType = self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'][0])
    {
        $request = $this->deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteRequest($contact_uuid, $affiliation_uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientHub\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteAsync
     *
     * Delete Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteAsync($contact_uuid, $affiliation_uuid, string $contentType = self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'][0])
    {
        return $this->deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteAsyncWithHttpInfo($contact_uuid, $affiliation_uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteAsyncWithHttpInfo
     *
     * Delete Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteAsyncWithHttpInfo($contact_uuid, $affiliation_uuid, string $contentType = self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'][0])
    {
        $returnType = '';
        $request = $this->deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteRequest($contact_uuid, $affiliation_uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDeleteRequest($contact_uuid, $affiliation_uuid, string $contentType = self::contentTypes['deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'][0])
    {

        // verify the required parameter 'contact_uuid' is set
        if ($contact_uuid === null || (is_array($contact_uuid) && count($contact_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contact_uuid when calling deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'
            );
        }

        // verify the required parameter 'affiliation_uuid' is set
        if ($affiliation_uuid === null || (is_array($affiliation_uuid) && count($affiliation_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $affiliation_uuid when calling deleteAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidDelete'
            );
        }


        $resourcePath = '/api/v1/contacts/{contact_uuid}/affiliations/{affiliation_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contact_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'contact_uuid' . '}',
                ObjectSerializer::toPathValue($contact_uuid),
                $resourcePath
            );
        }
        // path params
        if ($affiliation_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'affiliation_uuid' . '}',
                ObjectSerializer::toPathValue($affiliation_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet
     *
     * List Affiliations Endpoint
     *
     * @param  string $contact_uuid contact_uuid (required)
     * @param  bool|null $active_only active_only (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\ClientHub\Model\HTTPValidationError
     */
    public function listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet($contact_uuid, $active_only = true, string $contentType = self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'][0])
    {
        list($response) = $this->listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetWithHttpInfo($contact_uuid, $active_only, $contentType);
        return $response;
    }

    /**
     * Operation listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetWithHttpInfo
     *
     * List Affiliations Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  bool|null $active_only (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\ClientHub\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetWithHttpInfo($contact_uuid, $active_only = true, string $contentType = self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'][0])
    {
        $request = $this->listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetRequest($contact_uuid, $active_only, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\ClientHub\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ClientHub\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ClientHub\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientHub\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetAsync
     *
     * List Affiliations Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  bool|null $active_only (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetAsync($contact_uuid, $active_only = true, string $contentType = self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'][0])
    {
        return $this->listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetAsyncWithHttpInfo($contact_uuid, $active_only, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetAsyncWithHttpInfo
     *
     * List Affiliations Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  bool|null $active_only (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetAsyncWithHttpInfo($contact_uuid, $active_only = true, string $contentType = self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'][0])
    {
        $returnType = 'mixed';
        $request = $this->listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetRequest($contact_uuid, $active_only, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'
     *
     * @param  string $contact_uuid (required)
     * @param  bool|null $active_only (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGetRequest($contact_uuid, $active_only = true, string $contentType = self::contentTypes['listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'][0])
    {

        // verify the required parameter 'contact_uuid' is set
        if ($contact_uuid === null || (is_array($contact_uuid) && count($contact_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contact_uuid when calling listAffiliationsEndpointApiV1ContactsContactUuidAffiliationsGet'
            );
        }



        $resourcePath = '/api/v1/contacts/{contact_uuid}/affiliations';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $active_only,
            'active_only', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($contact_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'contact_uuid' . '}',
                ObjectSerializer::toPathValue($contact_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut
     *
     * Update Affiliation Endpoint
     *
     * @param  string $contact_uuid contact_uuid (required)
     * @param  string $affiliation_uuid affiliation_uuid (required)
     * @param  \ClientHub\Model\AffiliationUpdate $affiliation_update affiliation_update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return mixed|\ClientHub\Model\HTTPValidationError
     */
    public function updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut($contact_uuid, $affiliation_uuid, $affiliation_update, string $contentType = self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'][0])
    {
        list($response) = $this->updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutWithHttpInfo($contact_uuid, $affiliation_uuid, $affiliation_update, $contentType);
        return $response;
    }

    /**
     * Operation updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutWithHttpInfo
     *
     * Update Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  \ClientHub\Model\AffiliationUpdate $affiliation_update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'] to see the possible values for this operation
     *
     * @throws \ClientHub\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of mixed|\ClientHub\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutWithHttpInfo($contact_uuid, $affiliation_uuid, $affiliation_update, string $contentType = self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'][0])
    {
        $request = $this->updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutRequest($contact_uuid, $affiliation_uuid, $affiliation_update, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('mixed' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('mixed' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'mixed', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\ClientHub\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ClientHub\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ClientHub\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'mixed';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClientHub\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutAsync
     *
     * Update Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  \ClientHub\Model\AffiliationUpdate $affiliation_update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutAsync($contact_uuid, $affiliation_uuid, $affiliation_update, string $contentType = self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'][0])
    {
        return $this->updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutAsyncWithHttpInfo($contact_uuid, $affiliation_uuid, $affiliation_update, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutAsyncWithHttpInfo
     *
     * Update Affiliation Endpoint
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  \ClientHub\Model\AffiliationUpdate $affiliation_update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutAsyncWithHttpInfo($contact_uuid, $affiliation_uuid, $affiliation_update, string $contentType = self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'][0])
    {
        $returnType = 'mixed';
        $request = $this->updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutRequest($contact_uuid, $affiliation_uuid, $affiliation_update, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'
     *
     * @param  string $contact_uuid (required)
     * @param  string $affiliation_uuid (required)
     * @param  \ClientHub\Model\AffiliationUpdate $affiliation_update (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPutRequest($contact_uuid, $affiliation_uuid, $affiliation_update, string $contentType = self::contentTypes['updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'][0])
    {

        // verify the required parameter 'contact_uuid' is set
        if ($contact_uuid === null || (is_array($contact_uuid) && count($contact_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contact_uuid when calling updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'
            );
        }

        // verify the required parameter 'affiliation_uuid' is set
        if ($affiliation_uuid === null || (is_array($affiliation_uuid) && count($affiliation_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $affiliation_uuid when calling updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'
            );
        }

        // verify the required parameter 'affiliation_update' is set
        if ($affiliation_update === null || (is_array($affiliation_update) && count($affiliation_update) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $affiliation_update when calling updateAffiliationEndpointApiV1ContactsContactUuidAffiliationsAffiliationUuidPut'
            );
        }


        $resourcePath = '/api/v1/contacts/{contact_uuid}/affiliations/{affiliation_uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($contact_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'contact_uuid' . '}',
                ObjectSerializer::toPathValue($contact_uuid),
                $resourcePath
            );
        }
        // path params
        if ($affiliation_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'affiliation_uuid' . '}',
                ObjectSerializer::toPathValue($affiliation_uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($affiliation_update)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($affiliation_update));
            } else {
                $httpBody = $affiliation_update;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
